<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260208170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dish (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, image VARCHAR(255) DEFAULT NULL, width INT NOT NULL, height INT NOT NULL, stack_limit INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE shelf (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, width INT NOT NULL, height INT NOT NULL, x INT NOT NULL, y INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stack (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, x INT NOT NULL, y INT NOT NULL, width INT NOT NULL, height INT NOT NULL, count INT DEFAULT 1 NOT NULL, shelf_id INT NOT NULL, dish_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_stack_shelf ON stack (shelf_id)');
        $this->addSql('CREATE INDEX idx_stack_dish ON stack (dish_id)');
        $this->addSql('ALTER TABLE stack ADD CONSTRAINT FK_41A87B6A7C12FBC0 FOREIGN KEY (shelf_id) REFERENCES shelf (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stack ADD CONSTRAINT FK_41A87B6A148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stack DROP CONSTRAINT FK_41A87B6A7C12FBC0');
        $this->addSql('ALTER TABLE stack DROP CONSTRAINT FK_41A87B6A148EB0CB');
        $this->addSql('DROP TABLE dish');
        $this->addSql('DROP TABLE shelf');
        $this->addSql('DROP TABLE stack');
    }
}
