<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260207110812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dish (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, image VARCHAR(255) DEFAULT NULL, width INT NOT NULL, height INT NOT NULL, is_stacked BOOLEAN DEFAULT FALSE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE shelf (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, width INT NOT NULL, height INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE placement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, x INT NOT NULL, y INT NOT NULL, width INT NOT NULL, height INT NOT NULL, stack_id INT DEFAULT NULL, stack_index INT DEFAULT NULL, shelf_id INT NOT NULL, dish_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_placement_shelf ON placement (shelf_id)');
        $this->addSql('CREATE INDEX idx_placement_dish ON placement (dish_id)');
        $this->addSql('CREATE INDEX idx_placement_stack ON placement (stack_id)');
        $this->addSql('ALTER TABLE placement ADD CONSTRAINT FK_48DB750E7C12FBC0 FOREIGN KEY (shelf_id) REFERENCES shelf (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE placement ADD CONSTRAINT FK_48DB750E148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE dish');
        $this->addSql('DROP TABLE placement');
        $this->addSql('DROP TABLE shelf');
    }
}
